[package]
name = "dynamic-route53"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.0.26-alpha"
aws-sdk-route53 = "0.4.1"
tokio = { version = "1", features = ["full"] }
structopt = "0.3"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
