[package]
name = "dynamic-route53"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.0.23-alpha"
aws-sdk-route53 = "0.0.24-alpha"
tokio = { version = "1", features = ["full"] }
structopt = "0.3"
reqwest = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
